### ISSUE TITLE
Smart Home tiles no longer in power menu (Samsung Galaxy S9+ / v2.2)

### ISSUE THREAD

**Issue by liam-d99** [iodeOS/ota#10]
After updating to version 2.2 of iodeOS using the built in updater the smart home tiles are no longer showing up in my power menu (https://www.androidcentral.com/how-configure-smart-home-controls-android-11). This functionality worked with my Home Assistant setup (https://www.home-assistant.io/) before updating. Maybe there is some configuration that I have missed, but even after reinstalling home assistant on the phone I cannot seem to get the tiles to show up.

**Comment by vincentvidal** [comment]
Our issue tracker (the one that we closely follow and reference in our communication) is at gitlab.com/iode/ota, that's why you did not yet receive an answer, sorry.
Do you still have the issue ? And did you check that the parameter Settings -> System -> Power Menu -> Device controls is switched on ?

**Comment by vincentvidal** [comment]
Closing. Please open an issue on gitlab if needed.
